#pragma kernel CSMain

RWTexture3D<float> points;
int textureSize;
int3 brushCenter;
int brushRadius;
float deltaTime;
float weight;

// return smooth value between 0 and 1 (0 when t = minVal, 1 when t = maxVal)
float smoothstep(float minVal, float maxVal, float t)
{
    t = saturate((t - minVal) / (maxVal - minVal));
    return t * t * (3 - 2 * t);
}

[numthreads(8,8,8)]
void CSMain(int3 id : SV_DispatchThreadID)
{
    const int borderSize = 1;
    if (id.x >= textureSize - borderSize || id.y >= textureSize - borderSize || id.z >= textureSize - borderSize)
    {
        return;
    }
    if (id.x <= borderSize || id.y <= borderSize || id.z <= borderSize)
    {
        return;
    }

    int3 offset = id - brushCenter;
    int sqrDst = dot(offset, offset);

    if (sqrDst > brushRadius * brushRadius) return;
    float dst = sqrt(sqrDst);
    float brushWeight = 1 - smoothstep(brushRadius * 0.7, brushRadius, dst);
    float newValue = weight * deltaTime * brushWeight;
    points[id] += min(1, max(-1, newValue));
}
